sudo: required
services:
- docker
language: bash
env: 
  - ARCH=amd64
  - ARCH=arm
  - ARCH=aarch64
script:
# Setup QEMU for ARM image build
- docker run --rm --privileged multiarch/qemu-user-static:register
# Build image
- docker build -t diyhue/core:$ARCH -f ./.build/$ARCH.Dockerfile .
# Login, tag and push dev image
#- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
#- docker tag diyhue/core:$ARCH diyhue/core:$ARCH-dev
#- docker push diyhue/core:$ARCH-dev
# Pull dev image to run tests
- docker run -d --name "diyHue" --network="host" -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' -e 'MAC=b8:27:eb:d4:dc:11' -e 'IP=192.168.1.123' -e 'DECONZ=192.168.1.111' -e 'IP_RANGE=5,200' -e 'DEBUG=true' diyhue/core:$ARCH
# Wait for logs to populate, then list them
- sleep 30
- docker logs diyHue
# Kill and remove test container
- docker kill diyHue
- docker rm diyHue
- docker history diyhue/core:$ARCH
- docker images

before_deploy:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

deploy:
- provider: script # push arch and latest
  script: docker tag diyhue/core:$ARCH diyhue/core:$TRAVIS_BRANCH-$ARCH && docker push diyhue/core:$TRAVIS_BRANCH-$ARCH
  on:
    all_branches: true
    condition: $TRAVIS_PULL_REQUEST = false

- provider: script # push commit id
  script: docker tag diyhue/core:$ARCH diyhue/core:$TRAVIS_BRANCH-$ARCH-$TRAVIS_COMMIT && docker push diyhue/core:$TRAVIS_BRANCH-$ARCH-$TRAVIS_COMMIT
  on:
    all_branches: true
    condition: $TRAVIS_PULL_REQUEST = false

- provider: script # push versioning
  script: docker tag diyhue/core:$ARCH diyhue/core:$TRAVIS_TAG-$ARCH && docker push diyhue/core:$TRAVIS_TAG-$ARCH
  on:
    tags: true
    condition: $TRAVIS_PULL_REQUEST = false
jobs:
  include:
    - stage: push manifest
      script:
      - provider: script # push latest if master
        script: wget -O /tmp/manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 && chmod +x /tmp/manifest-tool && ./tmp/manifest-tool push from-args --ignore-missing --platforms linux/amd64,linux/arm --template "diyhue/core:$TRAVIS_BRANCH-ARCH" --target "diyhue/core:latest"
        on:
          branch: master
          condition: $TRAVIS_PULL_REQUEST = false

      - provider: script # push branch latest
        script: wget -O /tmp/manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 && chmod +x /tmp/manifest-tool && ./tmp/manifest-tool push from-args --ignore-missing --platforms linux/amd64,linux/arm --template "diyhue/core:$TRAVIS_BRANCH-ARCH" --target "diyhue/core:$TRAVIS_BRANCH-latest"
        on:
          all_branches: true
          condition: $TRAVIS_PULL_REQUEST = false

      - provider: script # push commit id
        script: wget -O /tmp/manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 && chmod +x /tmp/manifest-tool && ./tmp/manifest-tool push from-args --ignore-missing --platforms linux/amd64,linux/arm --template "diyhue/core:$TRAVIS_BRANCH-ARCH-${TRAVIS_COMMIT}" --target "diyhue/core:$TRAVIS_BRANCH-${TRAVIS_COMMIT}"
        on:
          all_branches: true
          condition: $TRAVIS_PULL_REQUEST = false

      - provider: script # push versioning
        script: wget -O /tmp/manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 && chmod +x /tmp/manifest-tool && ./tmp/manifest-tool push from-args --ignore-missing --platforms linux/amd64,linux/arm --template "diyhue/core:$TRAVIS_BRANCH-ARCH-${TRAVIS_TAG}" --target "diyhue/core:$TRAVIS_BRANCH-${TRAVIS_TAG}"
        on:
          tags: true
          condition: $TRAVIS_PULL_REQUEST = false

notifications:
slack: diyhue:84x97ehqLW4B6pe9ntP16SOI
