sudo: required
services:
- docker
language: bash
env:
  - ARCH=x86
  - ARCH=arm
script:
- docker run --rm --privileged multiarch/qemu-user-static:register
- docker build -t diyhue/core:$ARCH -f ./.build/$ARCH.Dockerfile  .
# test image
- docker run -d --name "diyHue" --network="host" -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' -e 'MAC=b8:27:eb:d4:dc:11' -e 'IP=192.168.1.123' diyhue/core:$ARCH

- sleep 10
- docker logs diyHue
- docker kill diyHue
- docker rm diyHue


# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker push diyhue/core:$ARCH
  fi